// A pre-registered report: the entire manuscript -- including the discussion
// of every possible outcome -- is written BEFORE the results exist. Nothing
// below contains a typed-in number or conclusion; all of it is computed from
// build/results.json, which scripts/analysis.py derives from data/. Rerun the
// *analysis* recipe (or change the data) and the prose updates itself.

#let R = json("build/results.json")
#let f(x, d: 2) = str(calc.round(x, digits: d))
#let dir = R.direction

#set page(margin: 2.2cm)
#set text(11pt)
#set par(justify: true)

#align(center)[
  #text(17pt, weight: "bold")[Thermal relaxation of a water sample in ambient air]
  #v(2pt)
  A pre-registered demonstration report #sym.dot generated #R.generated_utc
]

= Pre-registration
The hypotheses, decision rule, and the discussion text for *every* outcome in
this document were fixed before data collection. The decision rule: the
sample's temperature is deemed to have changed only if
$abs(T_2 - T_1) > 3 sigma$, where $sigma$ is the residual noise of a linear
fit. The report you are reading is therefore a pure function of the data:
identical inputs (integrity-pinned by sha256 in `scripts/fetch_data.py`)
reproduce it byte-for-byte.

= Methods
A water sample was left in contact with ambient air and its temperature
logged each minute (#R.n readings over #f(R.t_span_min, d: 0) minutes,
`data/experiment.csv`). $T_1$ and $T_2$ are the means of the first and last
three readings. `scripts/analysis.py` fits an ordinary least-squares trend
and, where applicable, Newton's law of cooling
$T(t) = T_"amb" + (T_1 - T_"amb") e^(-t\/tau)$ via a log-linear fit.

= Results
// The sentence the whole design exists for: its verb is computed.
The water was found to be
*#if R.T1 > R.T2 [cooling] else if R.T1 == R.T2 [constant] else [heating]*
when in contact with ambient air
(#f(R.T_ambient) #sym.degree\C): it moved from
$T_1 = #f(R.T1)$ #sym.degree\C to $T_2 = #f(R.T2)$ #sym.degree\C
(#if R.delta > 0 [+]#f(R.delta) #sym.degree\C), a mean trend of
#f(R.slope_c_per_min, d: 3) #sym.degree\C/min against residual noise of
#sym.plus.minus#f(R.noise_c, d: 2) #sym.degree\C.

#figure(
  image("figures/cooling.svg", width: 78%),
  caption: [Sample temperature vs. time. The fit line and its parameters are
    regenerated by every analysis run.],
)

#if R.newton != none [
  The relaxation is well described by Newton's law
  (#$R^2$ = #f(R.newton.r2, d: 3)) with rate constant
  $k = #f(R.newton.k_per_min, d: 3)$ min#super[-1], i.e. a time constant of
  $tau = #f(R.newton.tau_min, d: 1)$ minutes.
  #if R.newton.t_within_1c_min != none [
    The model predicts the sample reaches within 1 #sym.degree\C of ambient
    after about #f(R.newton.t_within_1c_min, d: 0) minutes.
  ]
] else [
  The temperature series did not admit a stable exponential fit, so no rate
  constant is reported.
]

= Discussion
// Every branch below was written before the data existed. Exactly one
// renders; which one is decided by the experiment, not the author.
#if dir == "cooling" [
  The observed decline is consistent with passive heat loss to the room: the
  sample began above ambient and relaxed toward it, as Newton's law predicts
  for a well-mixed body with surface-limited exchange. The practical
  implication in our pre-registration applies: samples prepared warm must be
  used within roughly one time constant if their temperature matters.
] else if dir == "heating" [
  A temperature *rise* was pre-registered as evidence that the sample started
  below ambient, or that an unaccounted heat source (stirring, exothermic
  contamination, direct sunlight) dominated passive exchange. The apparatus
  should be inspected before any physical interpretation is attempted.
] else [
  The change in temperature did not exceed three times the residual noise, so
  under the pre-registered rule we treat the sample as thermally constant
  over the observation window. This outcome was anticipated for samples
  prepared near ambient; a longer window or a larger initial offset would be
  required to detect exchange.
]

#if R.conclusive [
  Because the effect cleared the pre-registered threshold
  (|#f(R.delta)| #sym.gt 3 #sym.times #f(R.noise_c, d: 2)), we regard the
  direction stated above as the finding of this experiment.
] else [
  Because the effect did not clear the pre-registered threshold, this report
  makes *no* directional claim; by design, the wording above cannot overstate
  the evidence.
]

= Reproducibility
`just all` verifies the pinned data hash, reruns the analysis, and recompiles
this PDF and the summary. Editing prose recompiles instantly in the live
preview; editing `scripts/analysis.py` or `data/` regenerates every value on
this page. The build history, comments, and signed checkpoints travel with
the project's git repository.
